'use client';
import { useEffect, useRef } from 'react';
import Link from 'next/link';

const projects = [
  { number: '01', slug: 'insidely', title: 'Insidely', label: 'Product / Platform', description: 'Uma plataforma digital para conversas que abrem novas possibilidades.', accent: 'orange' },
  { number: '02', slug: 'casa-da-inovacao', title: 'Casa da\nInovação', label: 'Digital presence / Education', description: 'Informação, formação e presença digital para uma instituição em movimento.', accent: 'cream' },
];
function Mark() { return <span className="brand-mark" aria-hidden="true"><i /><i /><i /></span>; }

export default function Home() {
  const mainRef = useRef<HTMLElement>(null);
  useEffect(() => { const main = mainRef.current; if (!main) return; const onScroll = () => main.style.setProperty('--scroll', `${window.scrollY}`); const onMove = (event: MouseEvent) => { main.style.setProperty('--mx', `${(event.clientX / window.innerWidth - .5) * 2}`); main.style.setProperty('--my', `${(event.clientY / window.innerHeight - .5) * 2}`); }; window.addEventListener('scroll', onScroll, { passive: true }); window.addEventListener('mousemove', onMove, { passive: true }); return () => { window.removeEventListener('scroll', onScroll); window.removeEventListener('mousemove', onMove); }; }, []);
  return <main ref={mainRef} className="site-shell">
    <header className="nav wrap"><Link href="#top" className="wordmark" aria-label="Breno Silveira, início"><Mark /><span>BS / 26</span></Link><nav aria-label="Navegação principal"><a href="#work">Work</a><a href="#about">About</a><a href="#lab">Lab</a><a href="#contact">Contact</a></nav><div className="nav-end"><span className="availability"><b /> Open to possibilities</span><button aria-label="Alternar idioma">PT <span>/</span> EN</button></div></header>
    <section className="hero wrap" id="top"><div className="hero-top"><p className="eyebrow">Technology / AI / Digital experiences</p><span className="hero-index">( 00 — 04 )</span></div><div className="hero-content"><div className="hero-copy"><p className="kicker reveal">Creative technology<br />for the real world.</p><h1 className="hero-title">Breno<br /><em>Silveira</em></h1><p className="hero-intro">Transformo ideias em produtos digitais claros, úteis e com presença.</p></div><div className="signal-art" aria-label="Composição visual abstrata representando um sistema em construção" role="img"><div className="signal-core"><span>BS</span></div><div className="signal-ring ring-a" /><div className="signal-ring ring-b" /><div className="signal-line line-a" /><div className="signal-line line-b" /><div className="signal-caption">A / SYSTEM<br />IN MOTION</div></div></div><div className="hero-bottom"><span>Scroll to explore <i>↓</i></span><span className="hero-note">Building at the intersection<br />of logic and feeling.</span></div></section>
    <section className="intro-section wrap"><div className="section-label"><span>( 01 )</span><span>Selected work</span></div><p className="statement">Produtos digitais são feitos de decisões. Eu trabalho entre a pergunta certa e a coisa real que chega às mãos de alguém.</p></section>
    <section className="work-section" id="work"><div className="wrap"><div className="section-label"><span>( 02 )</span><span>Cases / 2024—26</span></div><div className="project-list">{projects.map((project) => <Link className={`project project-${project.accent}`} href={`/work/${project.slug}`} key={project.slug}><div className="project-meta"><span>{project.number}</span><span>{project.label}</span></div><div className="project-visual"><div className="visual-grid" /><div className="visual-ui"><span className="ui-top">{project.number} / {project.title.replace('\n',' ')}</span><strong>{project.accent === 'orange' ? 'Talks that\nmove things.' : 'Knowledge\nin motion.'}</strong><span className="ui-bottom">Explore case <i>↗</i></span></div></div><div className="project-info"><h2>{project.title.split('\n').map((line) => <span key={line}>{line}</span>)}</h2><p>{project.description}</p><span className="view-case">View case <b>↗</b></span></div></Link>)}</div></div></section>
    <section className="about-section wrap" id="about"><div className="section-label"><span>( 03 )</span><span>About / Approach</span></div><div className="about-grid"><h2>Curious by nature.<br /><em>Precise by practice.</em></h2><div className="about-body"><p>Sou estudante de Ciência da Computação, atuando na interseção entre tecnologia, educação e criação digital.</p><p>Uso IA como ferramenta de processo — para prototipar, pesquisar, construir e iterar com mais velocidade e intenção.</p><div className="about-tags"><span>AI-assisted development</span><span>Automation</span><span>Creative technology</span><span>UX / UI</span></div></div></div></section>
    <section className="lab-section wrap" id="lab"><div className="section-label"><span>( 04 )</span><span>Lab / Coming next</span></div><div className="lab-inner"><span className="lab-orbit">●</span><h2>Room for<br /><em>experiments.</em></h2><p>Um espaço para interfaces, agentes, motion studies e ideias que ainda estão encontrando sua forma.</p><span className="lab-status">[ collecting signals ]</span></div></section>
    <footer className="footer wrap" id="contact"><div className="section-label"><span>( 05 )</span><span>Contact / Say hello</span></div><h2>Let's build<br /><em>something real.</em></h2><div className="footer-bottom"><span>© Breno Silveira — 2026</span><div className="footer-links"><a href="mailto:seuemail@exemplo.com">Email ↗</a><a href="#contact">LinkedIn ↗</a><a href="#contact">GitHub ↗</a><a href="/Breno-Silveira-CV.pdf">Currículo ↗</a></div></div></footer>
  </main>;
}
