import Image from 'next/image';
import { Header } from '@/components/Header';
import { ProjectFeature } from '@/components/ProjectFeature';
import { projects } from '@/data/projects';
import { CapabilitiesSection } from '@/components/CapabilitiesSection';
import { TechMarquee } from '@/components/TechMarquee';
import { PageLoader } from '@/components/PageLoader';
import { MotionLayer } from '@/components/MotionLayer';

export default function Home() {
  return <main id="top" className="portfolio-page"><PageLoader /><MotionLayer />
    <Header />
    <section className="hero-section" aria-labelledby="hero-title"><div className="hero-grid-mark" /><div className="hero-copy"><p className="hero-kicker" data-motion="hero">Olá, eu sou</p><h1 id="hero-title">Breno<br /><span>Silveira</span></h1><p className="hero-role" data-motion="hero"><strong>Full Stack Developer &</strong><span>Creative Technologist</span><em>Web, IA, automação & experiências digitais.</em></p><p className="hero-description" data-motion="hero">Desenvolvo aplicações e soluções digitais de ponta a ponta, combinando desenvolvimento web, inteligência artificial, automação e experiências interativas.</p><a className="hero-link" data-motion="hero" href="#work">Ver projetos <span>↓</span></a></div><div className="hero-portrait-wrap" data-motion="hero-image"><div className="hero-portrait"><Image src="/images/profile.png" alt="Breno Silveira" fill sizes="(max-width: 800px) 78vw, 36vw" priority /></div></div></section>
    <TechMarquee />
    <section id="work" className="work-section" aria-labelledby="work-title"><div className="work-intro" data-motion="section"><div><p className="section-label">Meus Projetos</p><h2 id="work-title">Veja os projetos<br /><span>em destaque.</span></h2></div><p>Projetos reais que combinam desenvolvimento, inteligência artificial e soluções digitais.</p></div><div className="project-list">{projects.map((project) => <ProjectFeature key={project.slug} project={project} />)}</div></section>
    <CapabilitiesSection />
    <section id="about" className="about-section" aria-labelledby="about-title"><div className="about-lead" data-motion="section"><p className="section-label">Sobre</p><h2 id="about-title">Tecnologia com<br /><span>curiosidade.</span></h2></div><div className="about-copy" data-motion="about-copy"><p>Sou <strong>Breno Silveira</strong>, estudante de Ciência da Computação em fase final da graduação e profissional de tecnologia com experiência em desenvolvimento web, educação tecnológica e criação de soluções digitais.</p><p>Atualmente, atuo com <strong>programação, robótica e inclusão digital</strong>, além de desenvolver projetos envolvendo web, automação e inteligência artificial aplicada.</p><p>Uso a <strong>IA como ferramenta de criação, pesquisa, prototipação e desenvolvimento</strong>, buscando transformar ideias e problemas em soluções úteis, funcionais e bem construídas.</p><div className="about-highlights"><span>Foco atual</span><p>Full Stack <i>·</i> IA aplicada <i>·</i> Automação <i>·</i> Experiências digitais</p></div><a href="https://wa.me/5521973549107" target="_blank" rel="noreferrer">Vamos conversar ↗</a></div></section>
    <section id="contact" className="contact-section" aria-labelledby="contact-title"><div className="contact-grid"><div className="contact-lead" data-motion="section"><p className="section-label">Contato</p><h2 id="contact-title">Tem uma ideia?<br /><span>Vamos construir.</span></h2></div><div className="contact-details" data-motion="contact-details"><p className="contact-support">Vamos conversar sobre projetos, oportunidades e soluções digitais.</p><a className="contact-email" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=brenosilveiraleal@gmail.com&amp;su=Contato%20pelo%20portf%C3%B3lio&amp;body=Ol%C3%A1%20Breno%2C%0A%0A" target="_blank" rel="noreferrer">brenosilveiraleal@gmail.com <span>↗</span></a><div className="contact-socials"><a href="https://wa.me/5521973549107" target="_blank" rel="noreferrer">WhatsApp</a><a href="https://www.linkedin.com/in/breno-silveira-leal/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/BrenoSilveiraLeal" target="_blank" rel="noreferrer">GitHub</a><a href="https://drive.google.com/file/d/1Ndul6LeKdTYOTpgyiEN-W4yCvnD1IWnM/view?usp=sharing" target="_blank" rel="noreferrer">Currículo</a><a href="https://www.instagram.com/bsl_silveira/" target="_blank" rel="noreferrer">Instagram</a><a href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=brenosilveiraleal@gmail.com" target="_blank" rel="noreferrer">E-mail</a></div></div></div></section>
    <footer className="site-footer"><span className="footer-copyright">© 2026 Breno Silveira. Todos os direitos reservados.</span></footer>
  </main>;
}
