'use client';
import { useState } from 'react';

const projects = [
  { id: '01', title: 'Insidely', tag: 'AI / PRODUCT', text: 'Laboratório de produtos digitais e ideias em movimento.', href: 'https://insidely.vercel.app/', image: '/images/insidely-hero.png', tone: 'cyan' },
  { id: '02', title: 'Casa da Inovação', tag: 'EDU / WEB', text: 'Experiência digital para educação e novas possibilidades.', href: 'https://casadainovacao.vercel.app/', tone: 'violet' },
  { id: '03', title: 'Experimentos', tag: 'CODE / AUTOMATION', text: 'Protótipos, APIs e ferramentas para simplificar o trabalho.', href: 'https://github.com/BrenoSilveiraLeal', tone: 'lime' },
];

export default function Home() {
  const [open, setOpen] = useState(false);
  return <main className="os-page">
    <header className="topbar"><a className="brand" href="#home"><span className="brand-mark">+</span> bsl<span className="dim">/portfolio</span></a><div className="topbar-clock">BRA // 09.09.26 <span className="live-dot" /></div><button className="nav-toggle" onClick={() => setOpen(!open)} aria-label="Abrir menu">{open ? '×' : '☰'}</button><nav className={open ? 'show' : ''}><a href="#work">work</a><a href="#profile">profile</a><a href="#contact">contact</a></nav><div className="social-links"><a href="mailto:brenosilveiraleal@gmail.com">email</a><a href="https://www.instagram.com/bsl_silveira/" target="_blank" rel="noreferrer">instagram</a><a href="https://github.com/BrenoSilveiraLeal" target="_blank" rel="noreferrer">github</a><a href="https://www.linkedin.com/in/breno-silveira-leal/" target="_blank" rel="noreferrer">linkedin</a></div><a className="availability" href="mailto:brenosilveiraleal@gmail.com">● available</a></header>
    <div className="system-grid" id="home">
      <section className="terminal-hero"><div className="terminal-label"><span>01</span> / HELLO, WORLD</div><div className="terminal-title"><span className="prompt">&gt;</span><h1>building<br /><i>useful things</i></h1><span className="cursor" /></div><p className="hero-copy">Breno Silveira é desenvolvedor e creative technologist. Desenho e construo experiências digitais para ideias que merecem sair do papel.</p><div className="hero-meta"><span>based in Brazil</span><span>scroll to explore ↓</span></div></section>
      <section className="identity-panel"><div className="panel-head"><span>IDENTITY_SCAN</span><span>IMG_001</span></div><div className="portrait-frame"><img src="/images/profile.png" alt="Breno Silveira" /><span className="cross cross-a">+</span><span className="cross cross-b">+</span><span className="face-tag">BRENO<br />SILVEIRA</span></div><div className="panel-foot"><span>creative / technical</span><span>01—03</span></div></section>
    </div>
    <section className="ticker"><span>REACT</span><span>NEXT.JS</span><span>TYPESCRIPT</span><span>AI APPLIED</span><span>UX / UI</span><span>AUTOMATION</span></section>
    <section className="work-block" id="work"><div className="section-bar"><span>02 / SELECTED_OUTPUT</span><span>03 PROJECTS</span></div><div className="work-intro"><h2>things<br /><em>i&apos;ve made.</em></h2><p>Uma seleção do que tenho construído entre código, produto e curiosidade.</p></div><div className="project-grid">{projects.map((project) => <a className={`project-card ${project.tone}`} href={project.href} target="_blank" rel="noreferrer" key={project.id}><div className="project-visual">{project.image ? <img src={project.image} alt={`Tela do projeto ${project.title}`} /> : <iframe src={project.href} title={`Tela do projeto ${project.title}`} loading="lazy" />}<span className="project-id">{project.id}</span><span className="project-open">↗</span><strong>{project.title}</strong></div><div className="project-data"><span>{project.tag}</span><p>{project.text}</p><b>open case ↗</b></div></a>)}</div></section>
    <section className="profile-block" id="profile"><div className="section-bar"><span>03 / PROFILE</span><span>STATUS: CURIOUS</span></div><div className="profile-grid"><div><h2>human<br /><em>behind<br />the code.</em></h2></div><div className="profile-text"><p className="profile-lead">Eu acredito que tecnologia boa desaparece dentro de uma experiência boa.</p><p>Sou estudante de Ciência da Computação e criador da Insidely. Meu trabalho mistura pensamento de produto, interface e engenharia para transformar problemas complexos em soluções claras.</p><div className="stats"><div><b>∞</b><span>curiosidade</span></div><div><b>24/7</b><span>aprendendo</span></div><div><b>1</b><span>boa pergunta</span></div></div></div></div></section>
    <section className="contact-block" id="contact"><div className="section-bar"><span>04 / CONNECTION</span><span>OPEN_CHANNEL</span></div><div className="contact-content"><span className="signal">● signal is good</span><h2>let&apos;s make<br /><em>something real.</em></h2><a className="contact-link" href="mailto:brenosilveiraleal@gmail.com">brenosilveiraleal@gmail.com <b>↗</b></a><div className="contact-links"><a href="mailto:brenosilveiraleal@gmail.com">e-mail ↗</a><a href="https://www.instagram.com/bsl_silveira/" target="_blank" rel="noreferrer">instagram ↗</a><a href="https://github.com/BrenoSilveiraLeal" target="_blank" rel="noreferrer">github ↗</a><a href="https://www.linkedin.com/in/breno-silveira-leal/" target="_blank" rel="noreferrer">linkedin ↗</a></div></div><footer><span>© 2026 BSL</span><span>São Paulo, BR</span><div><a href="https://www.linkedin.com/in/breno-silveira-leal/" target="_blank" rel="noreferrer">LINKEDIN</a><a href="https://github.com/BrenoSilveiraLeal" target="_blank" rel="noreferrer">GITHUB</a><a href="https://www.instagram.com/bsl_silveira/" target="_blank" rel="noreferrer">INSTAGRAM</a></div></footer></section>
  </main>;
}
